# After env create, run manually:
# pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
# pip install "numpy<2"
name: PSPStain
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- scipy
- dominate
- pillow
- numpy<2
- packaging
- pip
- pip:
    - opencv-python==4.8.1.78
    - visdom
    - GPUtil
    - scikit-image
    - pytorch-msssim
    - matplotlib